### ISSUE TITLE
Implement "Search" functionality for a task.

### ISSUE THREAD

**Issue by syedraazi** [sharmaSagar01/comp-8967-assignment-2-todo-app#5]

**Comment by singh8x1** [comment]
Not done yet. can be done on the front end part

**Comment by sharmaSagar01** [comment]
Issues has been fixed and implement on the app. 

![image](https://user-images.githubusercontent.com/37947735/197611569-9a810e83-d3ae-4a30-96f2-4f32e3c21083.png)
